---
exp:
  name: 'cnn_mnist'
  experiment_dir: 'experiments/'
model:
  lr: 0.0002
  dropout: true
  beta1: 0.9
  beta2: 0.999
  clipvalue: 10
  clipnorm: 10
trainer:
  epoch_to_continue: 40
  num_epochs: 100
  batch_size: 128
  label_smoothing: false
  use_lr_decay: false
  save_checkpoint_freq: 10
  keep_checkpoint_freq: 20
  use_horovod: true